services:
  postgres:
    image: postgres:17
    container_name: profilm_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - profilm_db:/var/lib/postgresql/data  # Mount the volume here
    ports:
      - "5433:5432"

volumes:
  profilm_db:
    driver: local
