services:
  postgres:
    image: postgres:17
    container_name: profilm_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tmpfs: 
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"
      
volumes:
  postgres_data:
    driver: local